import "./globals.css";

import type { Metadata } from "next";
import Navbar from "@/components/Navbar.tsx";
import { ThemeProvider } from "next-themes";
import MusicPlayer from "@/components/MusicPlayer";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
    title: "Homepage",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${GeistSans.className} antialiased`}>
                <ThemeProvider
                    attribute={"class"}
                    defaultTheme="system"
                    enableSystem
                >
                    <div className="fixed left-0 top-0 -z-10 h-full w-full">
                        {/* Light Mode Background */}
                        <div className="absolute inset-0 -z-10 h-full w-full bg-white [background:radial-gradient(125%_125%_at_50%_10%,#fff_40%,#63e_100%)] dark:hidden" />

                        {/* Dark Mode Background */}
                        <div className="absolute inset-0 -z-10 h-full w-full hidden dark:block [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]" />
                    </div>
                    <Navbar />
                    {children}
                    <MusicPlayer />
                </ThemeProvider>
            </body>
        </html>
    );
}
