import "./globals.css";

import type { Metadata } from "next";
import Navbar from "@/components/Navbar.tsx";
import { ThemeProvider } from "next-themes";
import MusicPlayer from "@/components/MusicPlayer";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
    title: "Homepage",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${GeistSans.className} antialiased`}>
                <ThemeProvider
                    attribute={"class"}
                    defaultTheme="system"
                    enableSystem
                >
                    <Navbar />
                    {children}
                    <MusicPlayer />
                </ThemeProvider>
            </body>
        </html>
    );
}
