import "./globals.css";

import type { Metadata } from "next";
import Navbar from "@/components/Navbar.tsx";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";

const adellesans = localFont({
    src: [
        {
            path: "../fonts/adellesans-regular-webfont.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/adellesans-semibold-webfont.ttf",
            weight: "500",
            style: "semibold",
        },
        {
            path: "../fonts/adellesans-bold-webfont.ttf",
            weight: "600",
            style: "bold",
        },
        {
            path: "../fonts/adellesans-extrabold-webfont.ttf",
            weight: "700",
            style: "extrabold",
        },
    ],
    variable: "--font-adellesans", // optional if using CSS vars
});

export const metadata: Metadata = {
    title: "Homepage",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${adellesans.className} antialiased`}>
                <ThemeProvider
                    attribute={"class"}
                    defaultTheme="system"
                    enableSystem
                >
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
